[project]
name = "santa-tavern-2025"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datapizza-ai>=0.0.9",
    "datapizza-ai-clients-openai>=0.0.9",
    "pydantic>=2.12.5",
    "requests>=2.32.5",
]
